name: animated_app
description: A new Flutter project.

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter

  #For MVVM architecture
  stacked: ^2.3.13
  stacked_services: ^0.9.3


  #inversion of control
  injectable:

  cupertino_icons: ^1.0.2
  rive: ^0.10.1
  flutter_svg: ^1.1.6



dev_dependencies:
  flutter_test:
    sdk: flutter

  #For MVVM architecture
  build_runner: ^2.0.3
  stacked_generator:
  injectable_generator:

  # The "flutter_lints" package below contains a set of recommended lints to
  flutter_lints: ^2.0.0


# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/avatars/
    - assets/backgrounds/
    - assets/fonts/
    - assets/icons/
    - assets/rive_assets/
    - assets/shapes/



  # To add custom fonts to your application, add a fonts section here,
  fonts:
    - family: Intel
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
